import numpy as np

def levenshtein_distance(str1,str2):
    rows = len(str1) + 2
    cols = len(str2) + 2

    matrix = np.empty([rows,cols], dtype = "<U10")

    for i in range(0,len(str1)):
        matrix[i+2][0] = str1[i]
        matrix[i+1][1] = i
    for k in range(0,len(str2)):
        matrix[0][k+2] = str2[k]
        matrix[1][k+1] = k
    for i in range(0,len(str1)+1):
        matrix[i+1][1] = i
    for k in range(0,len(str2)+1):
        matrix[1][k+1] = k


    for i in range(2,len(str1)+2):
        for j in range(2,len(str2)+2):
            if matrix[i][0] == matrix[0][j]:
                matrix[i][j] = matrix[i-1][j-1]
            else:
                matrix[i][j] = min(int(matrix[i-1][j-1]),int(matrix[i][j-1]),int(matrix[i-1][j])) + 1
    print(matrix[rows-1][cols-1])
    print(" ")

myinputs = [
'TULABVQEDPVBLSXXAUIHGKKSXSGNCA TUZAIABQEDHFBLSXHDUIHGKKSXSGPCGA',
'VPNKXBKJXOOOMPJECW VPQOKGCXKJXROOOMPJEC',
'UZHKUJXILLEEMYLHBZDPTQHMQJ RZHIJIRLNLEEMLYLHBZDPTOMMQJ',
'OFWQWIYGCTTTRCKOODIRPQQ OFWQWNYCTRZKOOVJPQO',
'VQAMEGHFHNFKXCEFXUVJRODIUSATAVTOQ VZZAMNEGFHNFKXXEXUVJROPDIUJSATAVOQ',
'HQOADTVLVDHBVOGT HQOADTVLDPBVOG',
'QBDXGJMWLKNSPZDXLWH QBSDXGOMWLNSPZDXXWW',
'WAHQRYXECSDAVHFRN WAHQSRYXQCBSDAHVRN',
'FSSRGOYXNLGIQFOJOUUJTKBTZBLPHQCP FSSRGOYGNLGUIQFOAUPUJTKTZBLPHQCP',
'EBFZHATHUWFLALJGZPUIJLCLFE IBFZUATUHUWFLAJGTPUIEJLUF',
'QORKBWIOUXZLFHWAAYV QORKZWIOUXZLFHWAAYV',
'VGYVLSMKDWXJDZWQATCSOYB VYVLJSPKDWXQZQZTCSYW',
'LGZWIMDEICHISOEFSBNKYZSWCPZHJCJPWTXGSDR LGZWIMPEICHISOEFXBNKYZSWCPPHJCJWTXGSDR',
'IGUAESRGPXPFXAKUWBTXBFMUGYSTHKUK RHGUAESRGWEPXPFWFTXBMUGYSTHKUK',
'LKTGLHWUJNCYMUNCGQZBHHPTRG LTZLWUJBNCYMNUNGGQZBHHPTRPBG',
'TORUUVINPPYLSURMAOOEWSVFB TCUUVNINPISURMAOOEWSVHFB',
'BTNOSWXAKDDPDZTU BTOSWKDDPDZTU',
'ORHMLNZCXNKGVKVIR ORHMLNZCXNKWGVKVIRB',
'CGLEHNKAYNZVBYAMXM MTCGZEONAYNZBAMXZ',
'CHZUSALEPDQBYQLDKZCISVPTVZWQY CHZMSALERPJQXBWMYQNLDKLCSVPTVZWQY',
'XUQIYBCIFQPLALEOAUBSXEVWKVNYFNMBLE XUQVYBCIVFAQLALEOAUBPSXBGVKUZNYFNNBTLE',
'DVZIXIFSKNQVRIZXOVSJZASLCTPFCY DVZIXIFSLNQVRIAZXOVTJASLTOPFDCY',
'SYKRWYSMDJUVBVPAM UYKRWYPMDJUVBVPAM',
'JGEEYFZHXIIGJUDLHYCKBHFRXICOGJZU GGEEEYFZHXIIGJDLHYVCKBHRXNIXZOJZU',
'CGCPZTSQMELFYUAWCMKIJRQWHKBHKXJOPUX CGCPZTJMCLFYTAWCMKIJRQWDKBHWXJOPUKA',
'YGYPLOJEMGWDISIMDDYMTZAXTH YYLOJMIWDISIMDDIYMTZQXTL',
'KBESCWJOOAKUEWNDGTJBLAJHGLWIM KBETCZJSDOAKUEWNZWGTXIAJCHGILAIP',
'DXYRSSKUVPQPENACYWWLUOYEQFTVKISHDJJ DXYRLUSKUVQPETACYWWAUOYEQTVKIHDJJ',
'DBTWALLBGBJWMFELKXJNDQSWLCC DBTALBGBJWMFELKZXJNDSWCC'
]

for i in myinputs:
    mylist = i.split()
    levenshtein_distance(mylist[0],mylist[1])
